/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaceGraphique;

import gestioncompetences.Competence;
import gestioncompetences.Competence;
import gestioncompetences.Competence;
import gestioncompetences.Employe;
import gestioncompetences.Employe;
import gestioncompetences.Employe;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;
import java.util.ArrayList;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author attma
 */
public class FicheEmployeFen extends javax.swing.JFrame {
    public static HashMap<Integer,Competence> comboBoxIdToCompetence= new HashMap<Integer,Competence>(); // pas top mais j ai pas trouvé mieux
    private String currentIdEmp;
    /**
     * Creates new form FicheEmployeFen
     */
    public FicheEmployeFen(Employe e) {
        initComponents();
        this.currentIdEmp = e.getIdentifiant();
        this.idEmp.setText(e.getIdentifiant());
        this.dateEmp.setText(e.getDate().toString());
        this.prenomEmp.setText(e.getPrenom());
        this.nomEmp.setText(e.getNom());
        initialiserListe(e);
        
        initialiserComboBox();
    }
    private void initialiserListe(Employe e) {
        Set<Competence> s = e.getCompetences();
       DefaultListModel modele = new DefaultListModel();
        for (Competence c : s) {
            modele.addElement(c.toString());
            System.out.println(c.toString());
        }
        this.listCompetences.setModel(modele);
    }

    private void initialiserComboBox(){
        DefaultComboBoxModel modele2 = new DefaultComboBoxModel() {};
        ArrayList<Competence> a= Competence.getCompetenceList();
        for (Competence c : a) {
            modele2.addElement(c.getLibelleFr());
            comboBoxIdToCompetence.put(modele2.getIndexOf(c.getLibelleFr()),c);
            System.out.println(c.getLibelleFr());
        }
        this.addCompetenceComboBox.setModel(modele2);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFicheEmp = new javax.swing.JPanel();
        jPanelInfosEmp = new javax.swing.JPanel();
        nomLib = new javax.swing.JLabel();
        nomEmp = new javax.swing.JLabel();
        prenomLib = new javax.swing.JLabel();
        dateLib = new javax.swing.JLabel();
        prenomEmp = new javax.swing.JLabel();
        dateEmp = new javax.swing.JLabel();
        idLib = new javax.swing.JLabel();
        idEmp = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanelInfosCompetencesDEmp = new javax.swing.JPanel();
        addCompetenceComboBox = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listCompetences = new javax.swing.JList<>();
        addCompToEmp = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        errorAddComp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 300));

        jPanelFicheEmp.setBackground(new java.awt.Color(51, 255, 102));
        jPanelFicheEmp.setLayout(new javax.swing.BoxLayout(jPanelFicheEmp, javax.swing.BoxLayout.PAGE_AXIS));

        jPanelInfosEmp.setMaximumSize(new java.awt.Dimension(3000, 100));
        jPanelInfosEmp.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanelInfosEmp.setName(""); // NOI18N
        jPanelInfosEmp.setPreferredSize(new java.awt.Dimension(130, 240));

        nomLib.setText("Nom :");

        nomEmp.setText("jLabel2");

        prenomLib.setText("Prénom :");

        dateLib.setText("Date :");

        prenomEmp.setText("jLabel4");

        dateEmp.setText("jLabel8");

        idLib.setText("Id :");

        idEmp.setText("jLabel6");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("FICHE EMPLOYE");

        javax.swing.GroupLayout jPanelInfosEmpLayout = new javax.swing.GroupLayout(jPanelInfosEmp);
        jPanelInfosEmp.setLayout(jPanelInfosEmpLayout);
        jPanelInfosEmpLayout.setHorizontalGroup(
            jPanelInfosEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfosEmpLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanelInfosEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelInfosEmpLayout.createSequentialGroup()
                        .addComponent(idLib)
                        .addGap(111, 111, 111)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelInfosEmpLayout.createSequentialGroup()
                        .addGroup(jPanelInfosEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(prenomLib)
                            .addComponent(nomLib)
                            .addComponent(dateLib))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelInfosEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomEmp)
                            .addComponent(prenomEmp)
                            .addComponent(idEmp)
                            .addComponent(dateEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jPanelInfosEmpLayout.setVerticalGroup(
            jPanelInfosEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInfosEmpLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanelInfosEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idEmp)
                    .addComponent(idLib))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInfosEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomEmp)
                    .addComponent(nomLib))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelInfosEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prenomLib)
                    .addComponent(prenomEmp))
                .addGap(18, 18, 18)
                .addGroup(jPanelInfosEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateLib)
                    .addComponent(dateEmp))
                .addGap(57, 57, 57))
        );

        jPanelFicheEmp.add(jPanelInfosEmp);

        jPanelInfosCompetencesDEmp.setBackground(new java.awt.Color(204, 204, 204));

        addCompetenceComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        addCompetenceComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCompetenceComboBoxActionPerformed(evt);
            }
        });

        listCompetences.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listCompetences);

        addCompToEmp.setText("+");
        addCompToEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addCompToEmpMouseClicked(evt);
            }
        });

        jLabel1.setText("Ses compétences : ");

        errorAddComp.setBackground(new java.awt.Color(255, 204, 204));
        errorAddComp.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanelInfosCompetencesDEmpLayout = new javax.swing.GroupLayout(jPanelInfosCompetencesDEmp);
        jPanelInfosCompetencesDEmp.setLayout(jPanelInfosCompetencesDEmpLayout);
        jPanelInfosCompetencesDEmpLayout.setHorizontalGroup(
            jPanelInfosCompetencesDEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfosCompetencesDEmpLayout.createSequentialGroup()
                .addGroup(jPanelInfosCompetencesDEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInfosCompetencesDEmpLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(addCompetenceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addCompToEmp))
                    .addGroup(jPanelInfosCompetencesDEmpLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelInfosCompetencesDEmpLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelInfosCompetencesDEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(errorAddComp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInfosCompetencesDEmpLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanelInfosCompetencesDEmpLayout.setVerticalGroup(
            jPanelInfosCompetencesDEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInfosCompetencesDEmpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInfosCompetencesDEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addCompetenceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addCompToEmp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(errorAddComp)
                .addGap(42, 42, 42))
        );

        jPanelFicheEmp.add(jPanelInfosCompetencesDEmp);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFicheEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFicheEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addCompetenceComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCompetenceComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addCompetenceComboBoxActionPerformed

    private void addCompToEmpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCompToEmpMouseClicked
        // On recup la competence
        Competence compAAdd= FicheEmployeFen.comboBoxIdToCompetence.get(addCompetenceComboBox.getSelectedIndex());
        if(Employe.mapEmployes.get(this.currentIdEmp).getCompetences().contains(compAAdd)){
            this.errorAddComp.setText("L'employé possède déjà cette compétence");
        }else{
            this.errorAddComp.setText(" ");
            // On l'ajoute à l'employé
            Employe.mapEmployes.get(this.currentIdEmp).ajouterCompetence(compAAdd);
            // On refresh la liste
            initialiserListe(Employe.mapEmployes.get(this.currentIdEmp));
        }
        
    }//GEN-LAST:event_addCompToEmpMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FicheEmployeFen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FicheEmployeFen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FicheEmployeFen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FicheEmployeFen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Employe e = null;
                new FicheEmployeFen(e).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCompToEmp;
    private javax.swing.JComboBox<String> addCompetenceComboBox;
    private javax.swing.JLabel dateEmp;
    private javax.swing.JLabel dateLib;
    private javax.swing.JLabel errorAddComp;
    private javax.swing.JLabel idEmp;
    private javax.swing.JLabel idLib;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanelFicheEmp;
    private javax.swing.JPanel jPanelInfosCompetencesDEmp;
    private javax.swing.JPanel jPanelInfosEmp;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listCompetences;
    private javax.swing.JLabel nomEmp;
    private javax.swing.JLabel nomLib;
    private javax.swing.JLabel prenomEmp;
    private javax.swing.JLabel prenomLib;
    // End of variables declaration//GEN-END:variables

    
}
