/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaceGraphique;

/**
 *
 * @author mutatep
 */
public class Main extends javax.swing.JPanel {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.jSplitPane1.setResizeWeight(0.5);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        GestionDeEmployesButton = new javax.swing.JButton();
        GestionDesMissionsButton = new javax.swing.JButton();

        GestionDeEmployesButton.setText("Gestion des employés");
        GestionDeEmployesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestionDeEmployesButtonActionPerformed(evt);
            }
        });
        jSplitPane1.setLeftComponent(GestionDeEmployesButton);

        GestionDesMissionsButton.setText("Gestion des missions");
        GestionDesMissionsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GestionDesMissionsButtonMouseClicked(evt);
            }
        });
        jSplitPane1.setRightComponent(GestionDesMissionsButton);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void GestionDeEmployesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestionDeEmployesButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GestionDeEmployesButtonActionPerformed

    private void GestionDesMissionsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GestionDesMissionsButtonMouseClicked
         
    }//GEN-LAST:event_GestionDesMissionsButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GestionDeEmployesButton;
    private javax.swing.JButton GestionDesMissionsButton;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
